name: zip_Dsc_Resources

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - DSCScripts/**
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  zip_it_up:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

    - name: Create a Zip file
      id: zip
      shell: pwsh
      run: |
          $ErrorActionPreference = "Stop"

          $tempLocation = (Join-Path $env:GITHUB_WORKSPACE '.\temp\')

          # clean up temp package folder
          if (test-path $tempLocation) {
              Remove-Item $tempLocation -Recurse -Confirm:$false -Force
          }
        
          $null = New-Item $tempLocation -Type Directory


          $zipFiles = Get-ChildItem .\DSCScripts\ *.ps1
          
          write-output 'we found the following files to zip:'
          $zipFiles

          foreach ($zf in $zipFiles) {
            write-host ('zipping file: {0}' -f $zf.FullName)
            Compress-Archive -Path $zf.FullName -DestinationPath (Join-Path $tempLocation ('{0}.zip' -f $zf.Name))
          }

          # set zipPath to env variable
          "zipPath=$tempLocation" >> $env:GITHUB_ENV

          GCI $tempLocation -recurse
        
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: 'a new release of dsc scripts'
        files: |
          /home/runner/work/BitsAndBobs/BitsAndBobs/temp/DomainControllerConfig.zip